### ISSUE TITLE
Criar propriedades para as classes

### ISSUE THREAD

**Issue by lucas-aguirre** [lucas-aguirre/Jogo-de-Guerra#17]
Saúde: A quantidade de dano necessário para exterminar a unidade. Quando chegar a Zero a unidade é eliminada do tabuleiro.

Velocidade: A quantidade de casas que a unidade pode andar.

Ataque: A quantidade de dano que um ataque da unidade irá infligir no inimigo.

Alcance: O alcance dos ataques da unidade.

**Comment by misaelsz** [comment]
As propriedades já estão criadas com nomes diferentes
