### ISSUE TITLE
Criar Model e Factory restantes

### ISSUE THREAD

**Issue by lucas-aguirre** [lucas-aguirre/Jogo-de-Guerra#8]
Criar o model e factorys para o nosso exército (astecas) e aplicar com command no wpf (não sei se é necessário mas é bom fazer como ele fez para ficar de boas).

Seria interessante também pensar em uma tabela para armazenar o estado atual da batalha, por exemplo, todas as peças que estão em jogo e seus status.

Antes de criar as classes seria bom dar uma olhada na tarefa #17 pois tem as propriedades de algumas classes lá e já seria bom implementar.

**Comment by misaelsz** [comment]
as models e factorys foram implementadas só validar e pensar como sera guardado a informação do estado da peça

**Comment by misaelsz** [comment]
validar e dar merge para branch master
